version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: chalkak-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - chalkak-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: chalkak-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - chalkak-network

volumes:
  redis_data:
    driver: local

networks:
  chalkak-network:
    driver: bridge
